name: Echo Greeting

on:
  workflow_dispatch:
    inputs:
      greeting:
        description: 'Greeting message'
        required: true

jobs:
  echo-greeting:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Greeting
        run: echo "Greeting: ${{ github.event.inputs.greeting }}"