name: "Deploy Policies"

on:
  workflow_dispatch:
    inputs:
      stage:
        description: "AZURE environment to deploy"
        required: true
        type: choice
        options: ['DEV', 'QA', 'UAT', 'PROD']
        default: DEV

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona